<?php

namespace Database\Seeders;

use App\Models\Entrevista;
use Illuminate\Database\Seeder;

class EntrevistaSeeder extends Seeder
{
    public function run(): void
    {
        $docentes = [

            // ── D-01 · CTP · 8-15 años · escéptico moderado ──────────────────
            [
                'codigo_participante' => 'D-01',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'CTP Roberto Gamboa Valverde',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '8 a 15 años',
                'cursos_actuales'     => 'Programación I, Programación II, Tecnologías Web',
                'resp_cat1_p1' => 'La mayor dificultad que observo es el salto conceptual entre escribir instrucciones secuenciales y pensar en objetos con responsabilidades propias. Los estudiantes memorizan sintaxis pero no internalizan por qué se separa el código en clases. El bloqueo más frecuente ocurre cuando tienen que diseñar una solución desde cero, sin un molde que copiar. La diferencia entre aprender sintaxis y diseñar un sistema complejo es abismal: la sintaxis se puede repetir mecánicamente, pero el diseño exige comprensión profunda que no se logra en pocas semanas.',
                'resp_cat1_p2' => 'Definitivamente sí. El problema se manifiesta cuando entregan código donde todo está en el main o en una sola clase enorme. No hay separación de responsabilidades, mezclan lectura de datos con lógica de negocio con presentación en el mismo método. Esto se vuelve más evidente en Programación II, cuando los proyectos crecen y el código se vuelve inmanejable. En décimo y undécimo año es donde más lo noto.',
                'resp_cat1_p3' => 'He probado varias cosas. Lo que mejor ha funcionado es comenzar con diagramas antes de escribir una sola línea de código — obligarlos a pensar en papel primero. También ayuda mucho la revisión de código entre pares, porque explicarle el código a otro fuerza la comprensión real. Lo que no ha funcionado bien son los laboratorios guiados paso a paso, porque los estudiantes los siguen mecánicamente sin entender el razonamiento detrás.',
                'resp_cat2_p1' => 'Sí, lo he observado bastante, especialmente en los últimos dos años. La mayoría lo usa para generar código que luego pegan sin entender. Lo noto de manera indirecta: el código tiene un estilo inconsistente con lo que han entregado antes, o usan construcciones avanzadas que no hemos visto en clase. Algunos lo hacen abiertamente, sobre todo para resolver dudas de sintaxis o errores de compilación.',
                'resp_cat2_p2' => 'El principal problema es la dependencia. Estudiantes que son incapaces de resolver un problema simple sin consultar la IA. En cuanto a deshonestidad académica, he tenido casos donde claramente el proyecto completo fue generado por IA. La diferencia en comprensión real es notable: quien usa la IA para generar y no para aprender llega al examen y no puede explicar cómo funciona su propio código.',
                'resp_cat2_p3' => 'En el CTP no existe ninguna normativa clara todavía. Queda al criterio de cada docente. Yo personalmente la permito para consultas puntuales pero prohíbo que se use para generar soluciones completas. He modificado mis evaluaciones para incluir más componente oral, donde el estudiante debe explicar y defender su código — eso hace más difícil que use IA sin entender.',
                'resp_cat3_p1' => 'Sí, creo que tiene potencial pedagógico real, pero requiere orientación. Lo veo útil para explicar mensajes de error, para que el estudiante pueda reformular una pregunta de varias maneras hasta entender un concepto, o para recibir retroalimentación inmediata sobre su código. La imagino más útil como herramienta del estudiante, pero bajo guía docente clara sobre cómo usarla correctamente.',
                'resp_cat3_p2' => 'Estaría dispuesto a adoptarla si es práctica, si no requiere demasiado tiempo de adaptación, y si está alineada con los objetivos del MEP. Lo que más resistencia me generaría es si implica que los estudiantes dependan de la IA para todo, o si la guía no está adaptada al nivel de secundaria técnica. Necesitaría ver evidencia de que funciona antes de comprometerme completamente.',
                'resp_cat3_p3' => 'La diferencia es enorme. El que pide código directamente obtiene una respuesta que no puede evaluar ni adaptar. El que pide que le expliquen el razonamiento de diseño está aprendiendo a pensar. He visto muy pocos estudiantes que usen la IA de esa segunda manera de forma espontánea, generalmente son los que ya tienen una base sólida. Es una habilidad que habría que enseñar explícitamente.',
                'resp_cat4_p1' => 'El acceso no es equitativo. Hay estudiantes de zonas rurales o con bajos recursos que solo tienen acceso a internet en la institución. En el aula contamos con computadoras, pero en casa muchos trabajan desde el celular con datos limitados. Esto genera una brecha real cuando se asignan tareas que requieren herramientas en línea fuera de clase.',
                'resp_cat4_p2' => 'He escuchado mencionar la Estrategia Nacional de IA del MEP pero no conozco los detalles de su implementación para 2026. En cuanto a capacitación institucional, hemos recibido algunos talleres generales sobre tecnología educativa, pero nada específico sobre IA generativa en programación. Básicamente cada docente ha tenido que aprender por su cuenta.',
                'resp_cierre'  => 'Creo que el tema más urgente es formar a los docentes primero, antes de pedirles que guíen a los estudiantes con IA. No se puede enseñar lo que no se sabe usar bien. Agradezco que se investigue esto desde el contexto costarricense.',
                'observaciones' => '',
            ],

            // ── D-02 · CTP · 3-7 años · entusiasta ──────────────────────────
            [
                'codigo_participante' => 'D-02',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'CTP Roberto Gamboa Valverde',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '3 a 7 años',
                'cursos_actuales'     => 'Programación I, Base de Datos, Soporte Técnico',
                'resp_cat1_p1' => 'La dificultad más común que veo es la abstracción. Pasar de "la computadora ejecuta instrucciones" a "los objetos tienen estado y comportamiento" es conceptualmente difícil. El bloqueo más frecuente es en el momento de instanciar objetos: los estudiantes confunden la clase con el objeto. Sí hay diferencia entre sintaxis y diseño: la sintaxis la aprenden relativamente rápido, pero diseñar un sistema coherente requiere una madurez conceptual que toma mucho más tiempo desarrollar.',
                'resp_cat1_p2' => 'Totalmente. La arquitectura por capas es el gran desafío de los cursos avanzados. Lo veo claramente en los proyectos finales: los estudiantes hacen consultas SQL directamente desde los eventos del formulario, sin ninguna capa intermedia. Creen que funciona porque el programa corre, pero sin comprender que el mantenimiento sería un desastre. El problema se hace evidente desde Programación II.',
                'resp_cat1_p3' => 'He adoptado una metodología de proyectos incrementales: empezamos con un sistema muy pequeño y lo vamos complejizando semana a semana, siempre refactorizando para separar capas. También funciona bien mostrarles código "malo" y pedirles que identifiquen qué está mal. Lo que menos ha funcionado es el enfoque teórico puro con UML antes de ver código real: los aburre y no conectan con la práctica.',
                'resp_cat2_p1' => 'Sí, constantemente. Desde que apareció ChatGPT el cambio fue inmediato y drástico. Lo usan principalmente para generar código de tareas, resolver ejercicios y copiar explicaciones. La mayoría lo hace de forma abierta, incluso me preguntan si pueden usarlo. En mi caso, lo permito con ciertas condiciones porque veo que tarde o temprano va a ser parte de su entorno laboral.',
                'resp_cat2_p2' => 'El problema principal es que el estudiante entrega código que no puede explicar. En evaluaciones orales colapsan. También he notado que cuando la IA genera código con un error, el estudiante no lo detecta porque no entiende el código. En cuanto a deshonestidad, es complicado probarlo, pero sí he tenido casos obvios donde el código supera con creces el nivel del estudiante.',
                'resp_cat2_p3' => 'No existe normativa formal en el CTP aún. Yo personalmente permito el uso de IA como herramienta de consulta, similar a cómo se permite buscar en Google. He ajustado mis evaluaciones para que incluyan explicaciones en vivo del código y resolución de problemas en tiempo real, donde la IA no puede ayudar directamente.',
                'resp_cat3_p1' => 'Completamente válido. Creo que la IA puede ser un tutor disponible las 24 horas, que explica conceptos de múltiples maneras sin cansarse. La veo útil para generar ejercicios adicionales personalizados, para explicar errores de compilación, y para ayudar a depurar. La imagino como herramienta de ambos: del estudiante para aprender y del docente para preparar material.',
                'resp_cat3_p2' => 'Sí, la adoptaría con gusto. Lo que necesitaría es que sea flexible, no prescriptiva — que sugiera prompts pero que me permita adaptarlos a mi contexto. Lo que me generaría resistencia es que sea demasiado rígida o que asuma que todos los estudiantes tienen acceso igual a internet.',
                'resp_cat3_p3' => 'Es una diferencia fundamental. El que pide el código tiene la solución pero no tiene conocimiento. El que pide el razonamiento tiene una conversación real de aprendizaje. Lamentablemente he visto muy pocos estudiantes que usen la IA de la segunda manera de forma espontánea. La mayoría va por el camino más corto. Por eso creo que hay que enseñarles explícitamente a formular buenas preguntas.',
                'resp_cat4_p1' => 'El acceso es bastante desigual. En el aula sí tenemos computadoras para todos, pero en casa la situación varía mucho. Algunos estudiantes viven en zonas sin internet de calidad. Cuando asigno tareas que requieren IA, siempre hago espacio dentro de la clase para quienes no tienen acceso en casa.',
                'resp_cat4_p2' => 'He leído algo sobre la Estrategia Nacional de IA del MEP, pero todavía no ha llegado de manera concreta a las aulas. No hemos recibido capacitación formal. Hemos aprendido explorando por nuestra cuenta, en grupos de WhatsApp con otros docentes, viendo tutoriales. Es un aprendizaje informal que debería ser institucionalizado.',
                'resp_cierre'  => 'Me parece muy valioso que se investigue esto desde una perspectiva pedagógica y no solo tecnológica. La pregunta importante no es si permitir la IA, sino cómo integrarla para que realmente apoye el aprendizaje. Espero que esta investigación genere recomendaciones prácticas para los docentes de programación.',
                'observaciones' => '',
            ],

            // ── D-03 · CTP · +15 años · crítico ─────────────────────────────
            [
                'codigo_participante' => 'D-03',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'CTP Roberto Gamboa Valverde',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => 'Más de 15 años',
                'cursos_actuales'     => 'Programación I, Programación II, Programación Avanzada, Proyecto Integrador',
                'resp_cat1_p1' => 'Con más de quince años enseñando, he visto que las dificultades fundamentales no cambian: la abstracción, el pensamiento lógico secuencial, y la capacidad de descomponer un problema complejo en partes manejables. Los estudiantes se bloquean principalmente en la fase de análisis, antes de escribir código. La diferencia entre aprender sintaxis y diseñar sistemas es que la primera es memorización y la segunda es comprensión profunda — y la escuela secundaria técnica generalmente entrena bien la primera pero tiene poco tiempo para la segunda.',
                'resp_cat1_p2' => 'Es el problema central de los últimos años del técnico. Los estudiantes entregan proyectos funcionales pero con arquitectura terrible. Todo en una clase, métodos de doscientas líneas, acceso directo a la base de datos desde la interfaz. Es una consecuencia directa de enseñar con ejemplos pequeños donde la arquitectura por capas parece innecesaria. El problema se hace crítico en el Proyecto Integrador de undécimo año.',
                'resp_cat1_p3' => 'Lo que mejor ha funcionado en mi experiencia es refactorizar código existente — tomar un proyecto funcional pero mal estructurado y mejorarlo juntos en clase. También funciona muy bien la revisión entre pares con rúbricas específicas de arquitectura. Lo que no funciona es la clase magistral sobre patrones de diseño sin un proyecto real de fondo: los estudiantes no ven para qué sirve.',
                'resp_cat2_p1' => 'Lo observo con mucha preocupación. Antes de la IA generativa, cuando un estudiante copiaba de internet, al menos el código que copiaba era de algún humano que lo había entendido. Ahora copian código generado que puede tener errores sutiles o que usa librerías que no conocemos en el CTP. La mayoría lo hace de forma disimulada aunque lo noto fácilmente por el cambio de estilo y vocabulario en el código.',
                'resp_cat2_p2' => 'Los problemas son varios. Primero, la incapacidad de depurar: si la IA generó el código y tiene un error, el estudiante no puede arreglarlo porque no lo entiende. Segundo, he tenido casos claros de proyectos completamente generados por IA que el estudiante no puede explicar. Tercero, me parece que estamos formando técnicos que van a depender de herramientas que no entienden, lo cual es peligroso en el mercado laboral.',
                'resp_cat2_p3' => 'No existe normativa formal. Yo la prohíbo en evaluaciones y lo explicito en el contrato pedagógico desde la primera semana. Sin embargo, reconozco que es difícil de controlar fuera del aula. He reforzado la evaluación oral y el trabajo en clase para reducir el impacto. Creo que la institución necesita definir una política clara al respecto.',
                'resp_cat3_p1' => 'Con cierta resistencia, reconozco que podría tener uso pedagógico si se usa correctamente. No la veo útil para generar código, pero sí para que el estudiante dialogue con ella sobre conceptos: preguntar por qué algo funciona de cierta manera, pedir alternativas, pedir que le explique un error. El riesgo es que los estudiantes tomen el camino corto y la usen como máquina de copiar.',
                'resp_cat3_p2' => 'Estaría dispuesto a considerarla si está muy bien estructurada y si hay evidencia de que mejora el aprendizaje real, no solo el rendimiento académico a corto plazo. Me generaría mucha resistencia si implica más trabajo para el docente sin apoyo institucional, o si sustituye el pensamiento propio del estudiante.',
                'resp_cat3_p3' => 'La diferencia es la diferencia entre aprender y hacer trampa. Quien pide el código no aprende. Quien pide el razonamiento tiene una oportunidad de aprender si realmente reflexiona sobre la respuesta. En 15 años de docencia he visto muy pocos estudiantes que naturalmente usen cualquier recurso de esa segunda manera — la mayoría busca la solución, no la comprensión. Eso es un problema de cultura educativa que va más allá de la IA.',
                'resp_cat4_p1' => 'La brecha digital existe y es real. Tenemos estudiantes de zonas rurales con acceso limitado en casa. En la institución contamos con laboratorio, pero los tiempos son limitados. Cuando diseño actividades con tecnología siempre debo pensar en la equidad de acceso, porque no puedo asumir que todos tienen computadora e internet en casa.',
                'resp_cat4_p2' => 'Tengo conocimiento general de los lineamientos del MEP sobre tecnología educativa, pero no conozco específicamente la Estrategia Nacional de IA 2026 en detalle. En cuanto a capacitación, hemos recibido talleres generales de tecnología educativa, pero nada específico sobre IA generativa. La capacitación que tengo sobre el tema la he conseguido por iniciativa propia.',
                'resp_cierre'  => 'Mi preocupación principal es que estamos tan enfocados en adaptar la educación a la IA que olvidamos preguntarnos si esa adaptación realmente beneficia al estudiante a largo plazo. La capacidad de resolver problemas sin depender de herramientas externas es una competencia que el mercado laboral siempre va a valorar, independientemente de qué herramientas existan. No debemos sacrificar eso.',
                'observaciones' => '',
            ],

            // ── D-04 · Universidad · 8-15 años · pragmático ─────────────────
            [
                'codigo_participante' => 'D-04',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'Universidad Latina de Costa Rica',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '8 a 15 años',
                'cursos_actuales'     => 'Programación Orientada a Objetos, Arquitectura de Software, Taller de Proyectos',
                'resp_cat1_p1' => 'En el contexto universitario, la dificultad más profunda que encuentro es la transición del código que "funciona" al código que es correcto, mantenible y escalable. Los estudiantes de primer año llegan con la mentalidad de que si el programa corre, está bien. El bloqueo más crítico ocurre cuando tienen que integrar múltiples clases en un sistema cohesivo — el diseño holístico es lo más difícil. La diferencia entre sintaxis y diseño de sistemas es que la primera es una herramienta y la segunda es un arte que toma años desarrollar.',
                'resp_cat1_p2' => 'Es un problema recurrente en POO y en Arquitectura. Los estudiantes llegan a la universidad sin haber trabajado con capas. En el código que entregan predominan las clases "Dios" que hacen todo, la lógica de negocio mezclada con la interfaz, y el acceso directo a datos desde cualquier parte del sistema. La dificultad se hace más visible en los cursos de II y III año cuando los proyectos crecen en complejidad.',
                'resp_cat1_p3' => 'El enfoque que mejores resultados me ha dado es el aprendizaje basado en revisión de código de proyectos reales — repositorios de código abierto. Los estudiantes ven cómo se estructura código profesional antes de intentarlo ellos mismos. También funciona bien asignar roles dentro del equipo (arquitecto, desarrollador, tester) para que entiendan las responsabilidades separadas. Lo que no funciona es el análisis teórico de patrones sin aplicación inmediata.',
                'resp_cat2_p1' => 'Es muy frecuente y bastante abierto en la universidad. Los estudiantes universitarios, en general, no tienen vergüenza de admitir que usan ChatGPT o Claude. Lo usan para tareas, proyectos, y también para estudiar para los exámenes. Lo noto principalmente en el estilo del código — más idiomático de lo que corresponde a su nivel — y en los comentarios que explican perfectamente el código pero que el estudiante no puede parafrasear en persona.',
                'resp_cat2_p2' => 'El problema principal es la ilusión de comprensión: el estudiante cree que entiende porque tiene el código funcionando, pero cuando cambio una variable del problema en el examen, no puede adaptar la solución. He tenido casos de deshonestidad académica donde proyectos completos fueron generados por IA. Noto diferencia clara en los exámenes presenciales entre estudiantes que trabajan con IA de manera reflexiva y los que simplemente copian.',
                'resp_cat2_p3' => 'En la Universidad Latina tenemos un reglamento de integridad académica que menciona el uso de IA pero de manera general. A nivel de curso, yo permito el uso de IA como recurso de apoyo, pero en las entregas se debe documentar qué se usó y cómo. He modificado mis evaluaciones para incluir más componentes de presentación oral y resolución de problemas en tiempo real que no se pueden preparar con IA.',
                'resp_cat3_p1' => 'Absolutamente sí. La IA tiene un potencial enorme en la enseñanza de programación, especialmente para retroalimentación inmediata. Un estudiante a las 11 de la noche depurando un error no tiene acceso al docente, pero sí tiene acceso a la IA. La veo útil para ambos: para el estudiante como tutor disponible siempre, y para el docente para generar material didáctico diferenciado. El uso más valioso que imagino es como interlocutor de diseño: que el estudiante le explique su diseño a la IA y la IA le haga preguntas.',
                'resp_cat3_p2' => 'Sí, la adoptaría. Las condiciones serían que sea práctica, que esté basada en evidencia, y que tenga ejemplos concretos por tipo de actividad. Lo que más resistencia me generaría es si implica mucho tiempo adicional de preparación o si siento que la guía dicta cómo debo enseñar en lugar de apoyar mi práctica existente.',
                'resp_cat3_p3' => 'Es la diferencia entre usar una calculadora para verificar un resultado que ya calculaste, versus usar la calculadora sin saber hacer la operación. El estudiante que pide razonamiento está aprendiendo a pensar; el que pide código está tercializando el pensamiento. He visto algunos estudiantes avanzados usar la IA de manera sofisticada — como interlocutor para validar decisiones de diseño — pero son excepciones, no la norma.',
                'resp_cat4_p1' => 'En el contexto universitario el acceso es generalmente mejor que en secundaria, pero no es uniforme. Hay estudiantes que trabajan y estudian, que tienen recursos limitados, o que viven lejos de la universidad. Diría que la brecha en universidad es más de tiempo que de infraestructura: algunos estudiantes simplemente no tienen tiempo para explorar herramientas nuevas.',
                'resp_cat4_p2' => 'Conozco de forma general la Estrategia Nacional de IA del MEP, aunque no todos sus detalles. En la Universidad Latina hemos tenido algunas charlas informativas sobre IA y educación, pero no una capacitación estructurada sobre cómo integrarla pedagógicamente. La mayoría del conocimiento que tengo lo he desarrollado de forma autodidacta y compartiéndolo con colegas.',
                'resp_cierre'  => 'Me interesa destacar que la pregunta clave no es tecnológica sino pedagógica: ¿qué queremos que nuestros estudiantes aprendan a hacer por sí mismos? Una vez que tengamos claridad sobre eso, podremos definir dónde la IA ayuda y dónde obstaculiza. Esa claridad de objetivos de aprendizaje tiene que venir primero.',
                'observaciones' => '',
            ],

            // ── D-05 · Universidad · 3-7 años · innovador ───────────────────
            [
                'codigo_participante' => 'D-05',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'Universidad Latina de Costa Rica',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '3 a 7 años',
                'cursos_actuales'     => 'Fundamentos de Programación, Estructuras de Datos, Desarrollo Web',
                'resp_cat1_p1' => 'Como docente relativamente nuevo, lo que más me impacta es que los estudiantes llegan con una expectativa de que programar es "teclear" y que si el IDE no subraya nada en rojo, está bien. La abstracción — entender que el código es una representación de una solución a un problema real — es lo más difícil de transmitir. El bloqueo más frecuente es en el momento de plantear el problema antes de codificar. La diferencia entre sintaxis y diseño es que una se aprende en días y el otro se desarrolla con años de práctica reflexiva.',
                'resp_cat1_p2' => 'Sí, es un problema que aparece desde Estructuras de Datos y se profundiza en los cursos avanzados. Los estudiantes tienden a poner toda la lógica en el método main o en la interfaz de usuario. Cuando intento explicar por qué separar capas, la respuesta típica es "pero funciona igual". El reto pedagógico es hacerles ver que la arquitectura no es para hoy sino para el mantenimiento futuro.',
                'resp_cat1_p3' => 'He tenido buenos resultados con el "refactoring en vivo" durante la clase: tomo código que funciona pero está mal estructurado y lo mejoramos juntos, discutiendo cada decisión. También funciona bien conectar los conceptos con situaciones laborales reales — cuando les digo que en la empresa van a heredar código horrible y tendrán que entenderlo, prestan más atención al diseño. Los proyectos aislados sin continuidad no funcionan bien para enseñar arquitectura.',
                'resp_cat2_p1' => 'Es una realidad cotidiana. Los estudiantes de mi generación son nativos digitales y adoptan cualquier herramienta nueva inmediatamente. Lo usan abiertamente y yo lo facilito dentro de ciertos límites. Lo noto principalmente en la calidad del código que entregan versus la calidad de lo que hacen en clase: la brecha es grande cuando usan IA sin comprensión.',
                'resp_cat2_p2' => 'El problema más grave que he observado es la incapacidad de iterar: cuando la solución generada por IA no resuelve exactamente el problema, el estudiante no sabe cómo ajustarla. También he notado que los estudiantes que usan IA para generar código tienen dificultad mayor en los exámenes presenciales. En cuanto a deshonestidad, he tenido casos, pero prefiero rediseñar las evaluaciones para hacerlas más difíciles de resolver con IA que gastar energía en detectar y sancionar.',
                'resp_cat2_p3' => 'En mi materia permito el uso de IA con documentación explícita del proceso: el estudiante debe mostrar la conversación que tuvo con la IA, justificar las decisiones que tomó y explicar qué modificó. Esto transforma el uso de IA de una trampa en un proceso de aprendizaje documentado. La universidad no tiene todavía una política clara y unificada.',
                'resp_cat3_p1' => 'Creo que es una de las herramientas más poderosas que ha llegado a la educación en décadas, si se usa bien. La imagino muy útil para tutorías personalizadas, para generar variaciones de ejercicios, para explicar errores en lenguaje natural, y para que el estudiante practique la habilidad de formular preguntas precisas. La veo como herramienta principalmente del estudiante, pero con mediación pedagógica del docente.',
                'resp_cat3_p2' => 'La adoptaría con entusiasmo. Lo que necesitaría es que sea colaborativa — que los docentes podamos sugerir ajustes según nuestra experiencia — y que tenga ejemplos muy concretos y listos para usar. Lo que más resistencia me generaría es si la guía asume acceso tecnológico uniforme o si no considera las diferencias de contexto socioeconómico de nuestros estudiantes.',
                'resp_cat3_p3' => 'Es la diferencia entre consumir y aprender. Quien pide el código obtiene un resultado; quien pide el razonamiento desarrolla una competencia. He visto algunos estudiantes avanzados usar la IA de esa segunda manera, pero son pocos. Creo que es una habilidad metacognitiva que hay que enseñar deliberadamente — no surge sola. Es parte de lo que me parece más valioso de esta investigación: visibilizar esa diferencia.',
                'resp_cat4_p1' => 'El acceso en la universidad es relativamente bueno comparado con secundaria, pero hay estudiantes que trabajan tiempo completo y estudian de noche, con acceso limitado. La universidad tiene wifi en campus pero no todos los estudiantes pueden estar en campus regularmente. Cuando diseño actividades digitales siempre ofrezco alternativas para quienes tienen restricciones de acceso.',
                'resp_cat4_p2' => 'Conozco la existencia de la Estrategia Nacional de IA del MEP aunque no todos los detalles de implementación. En la Universidad Latina hemos tenido algunas sesiones informativas pero no capacitación pedagógica profunda sobre cómo integrar IA en el aula. Como docente relativamente joven, he explorado mucho por mi cuenta y creo que eso me pone en ventaja, pero no debería ser solo responsabilidad individual.',
                'resp_cierre'  => 'Me gustaría que esta investigación visibilice que el problema no es la IA en sí, sino la falta de marcos pedagógicos para integrarla. Los docentes necesitamos orientación práctica, no prohibiciones ni adopción ciega. Un conjunto de guías de prompts para enseñanza de programación sería un aporte muy concreto y valioso.',
                'observaciones' => '',
            ],

            // ── D-06 · Universidad · +15 años · reflexivo ───────────────────
            [
                'codigo_participante' => 'D-06',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'Universidad Latina de Costa Rica',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => 'Más de 15 años',
                'cursos_actuales'     => 'Programación Orientada a Objetos, Ingeniería de Software, Seminario de Investigación',
                'resp_cat1_p1' => 'Con quince años de experiencia universitaria, puedo afirmar que las dificultades fundamentales son constantes aunque el contexto cambie. La más persistente es la incapacidad de pensar en términos de responsabilidades: qué sabe cada componente y qué no debe saber. Los estudiantes se bloquean principalmente cuando tienen que tomar decisiones de diseño sin una respuesta "correcta" única. La brecha entre sintaxis y diseño de sistemas refleja la brecha entre saber hacer y saber pensar — la educación técnica tiende a desarrollar bien la primera y descuidar la segunda.',
                'resp_cat1_p2' => 'Es quizá el indicador más claro del nivel de madurez del estudiante como programador. En 15 años he visto la misma progresión: el estudiante aprende a hacer programas que funcionan, luego aprende a hacer programas que están bien estructurados, y finalmente aprende a hacer sistemas que otros pueden mantener. La mayoría de los estudiantes universitarios está en la primera etapa cuando deberían estar avanzando hacia la segunda. La arquitectura por capas requiere que primero entiendan por qué existe, no solo cómo implementarla.',
                'resp_cat1_p3' => 'A lo largo de los años he llegado a la conclusión de que el aprendizaje de diseño requiere práctica deliberada con retroalimentación experta. Lo que mejor funciona es la mentoría de código: revisiones frecuentes y conversacionales donde el estudiante justifica sus decisiones y yo las cuestiono. Los proyectos largos con hitos de revisión funcionan mucho mejor que los proyectos cortos sin revisión. Lo que no funciona es la exposición de reglas sin práctica: los estudiantes pueden recitar los principios SOLID y violarlos todos en el mismo proyecto.',
                'resp_cat2_p1' => 'Lo observo como un cambio estructural en la dinámica del curso, no como un evento aislado. Desde 2023 la forma en que los estudiantes abordan las tareas cambió notablemente. Ahora llegan a clase con código funcionando que no entienden, en lugar de llegar con código roto que intentaron resolver. La segunda situación es pedagógicamente más valiosa. Lo hacen mayoritariamente de forma abierta, porque la cultura universitaria actual lo normaliza.',
                'resp_cat2_p2' => 'El impacto más profundo que he observado es en la capacidad de resolución de problemas nuevos. Los estudiantes que usan la IA de forma acrítica tienen mayor dificultad para resolver problemas en contextos ligeramente diferentes a los del ejemplo. También he notado una disminución en la tolerancia a la frustración: si la IA no resuelve el problema en el primer intento, el estudiante se desespera en lugar de reflexionar. En cuanto a deshonestidad, prefiero transformar las evaluaciones que perseguir casos individuales.',
                'resp_cat2_p3' => 'En la Universidad Latina existe un reglamento de integridad académica actualizado en 2024 que incluye referencias al uso de IA, aunque de manera general. A nivel de carrera no hay política unificada todavía. Yo adopté hace dos años una política de transparencia: uso de IA permitido y documentado, con reflexión explícita sobre el proceso. Ha funcionado mejor que la prohibición, que era imposible de controlar.',
                'resp_cat3_p1' => 'Después de reflexionar mucho, sí creo que tiene potencial pedagógico real, pero requiere un diseño instruccional cuidadoso. La imagino más útil como herramienta socrática: que el estudiante la use para explorar, para hacerse preguntas, para validar su razonamiento — no para obtener respuestas. La veo como herramienta principalmente del estudiante, pero el docente tiene que diseñar las actividades que enmarquen ese uso de manera que propicie el aprendizaje real.',
                'resp_cat3_p2' => 'Sí, estaría dispuesto, con las condiciones adecuadas. Necesitaría que la guía sea fundamentada pedagógicamente, no solo tecnológicamente. Que explique el por qué de cada tipo de prompt, no solo el cómo. Lo que me generaría resistencia es si la guía está diseñada para docentes sin considerar las diferencias entre niveles educativos, disciplinas o contextos institucionales. Una guía para secundaria técnica y una para universidad tienen que ser distintas.',
                'resp_cat3_p3' => 'Es una distinción fundamental y muy poco explorada pedagógicamente. Quien pide el código está en una relación de dependencia con la herramienta. Quien pide el razonamiento está en una relación de diálogo epistémico — usa la IA como interlocutor para construir conocimiento. He visto eso muy pocas veces de forma espontánea, solo en estudiantes avanzados y curiosos. Enseñar a hacer esa segunda cosa debería ser uno de los objetivos centrales de cualquier guía pedagógica de uso de IA.',
                'resp_cat4_p1' => 'La inequidad de acceso es real incluso en la universidad privada. Hay estudiantes con recursos limitados, que trabajan, que no tienen computadora propia de calidad. En mis cursos siempre ofrezco alternativas para quienes tienen limitaciones, y trato de no diseñar actividades que requieran tecnología de alto costo o conexión permanente. La equidad de acceso es una consideración ética que no podemos ignorar.',
                'resp_cat4_p2' => 'Conozco bien la Estrategia Nacional de IA del MEP 2026 y he seguido su desarrollo. En la Universidad hemos tenido algunas jornadas de sensibilización, pero no capacitación pedagógica profunda. He participado en algunos espacios de formación externos por iniciativa propia. Creo que las universidades privadas en Costa Rica tienen un rezago importante en la preparación de sus docentes para integrar IA de manera pedagógicamente responsable.',
                'resp_cierre'  => 'Me parece fundamental que la investigación en este campo no se limite a describir el uso actual de la IA, sino que proponga marcos de acción concretos para los docentes. La pregunta relevante no es si los estudiantes usan IA — la usan y la usarán — sino cómo diseñamos experiencias de aprendizaje que hagan que ese uso sea genuinamente formativo y no una forma sofisticada de evadir el aprendizaje. Esa es la pregunta que su investigación está tratando de responder y me parece muy oportuna.',
                'observaciones' => '',
            ],

        ];

        foreach ($docentes as $data) {
            Entrevista::create($data);
        }
    }
}
