<?php

namespace Database\Seeders;

use App\Models\Entrevista;
use Illuminate\Database\Seeder;

class EntrevistaSeeder extends Seeder
{
    public function run(): void
    {
        $docentes = [

            // ── D-01 · CTP · 8-15 años · escéptico moderado ──────────────────
            [
                'codigo_participante' => 'D-01',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'CTP Roberto Gamboa Valverde',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '8 a 15 años',
                'cursos_actuales'     => 'Programación I, Programación II, Tecnologías Web',
                'resp_cat1_p1' => 'La mayor dificultad que observo es el salto conceptual entre escribir instrucciones secuenciales y pensar en objetos con responsabilidades propias. Los estudiantes memorizan sintaxis pero no internalizan por qué se separa el código en clases. El bloqueo más frecuente ocurre cuando tienen que diseñar una solución desde cero, sin un molde que copiar. La diferencia entre aprender sintaxis y diseñar un sistema complejo es abismal: la sintaxis se puede repetir mecánicamente, pero el diseño exige comprensión profunda que no se logra en pocas semanas.',
                'resp_cat1_p2' => 'Definitivamente sí. El problema se manifiesta cuando entregan código donde todo está en el main o en una sola clase enorme. No hay separación de responsabilidades, mezclan lectura de datos con lógica de negocio con presentación en el mismo método. Esto se vuelve más evidente en Programación II, cuando los proyectos crecen y el código se vuelve inmanejable. En décimo y undécimo año es donde más lo noto.',
                'resp_cat1_p3' => 'He probado varias cosas. Lo que mejor ha funcionado es comenzar con diagramas antes de escribir una sola línea de código — obligarlos a pensar en papel primero. También ayuda mucho la revisión de código entre pares, porque explicarle el código a otro fuerza la comprensión real. Lo que no ha funcionado bien son los laboratorios guiados paso a paso, porque los estudiantes los siguen mecánicamente sin entender el razonamiento detrás.',
                'resp_cat2_p1' => 'Sí, lo he observado bastante, especialmente en los últimos dos años. La mayoría lo usa para generar código que luego pegan sin entender. Lo noto de manera indirecta: el código tiene un estilo inconsistente con lo que han entregado antes, o usan construcciones avanzadas que no hemos visto en clase. Algunos lo hacen abiertamente, sobre todo para resolver dudas de sintaxis o errores de compilación.',
                'resp_cat2_p2' => 'El principal problema es la dependencia. Estudiantes que son incapaces de resolver un problema simple sin consultar la IA. En cuanto a deshonestidad académica, he tenido casos donde claramente el proyecto completo fue generado por IA. La diferencia en comprensión real es notable: quien usa la IA para generar y no para aprender llega al examen y no puede explicar cómo funciona su propio código.',
                'resp_cat2_p3' => 'En el CTP no existe ninguna normativa clara todavía. Queda al criterio de cada docente. Yo personalmente la permito para consultas puntuales pero prohíbo que se use para generar soluciones completas. He modificado mis evaluaciones para incluir más componente oral, donde el estudiante debe explicar y defender su código — eso hace más difícil que use IA sin entender.',
                'resp_cat3_p1' => 'Sí, creo que tiene potencial pedagógico real, pero requiere orientación. Lo veo útil para explicar mensajes de error, para que el estudiante pueda reformular una pregunta de varias maneras hasta entender un concepto, o para recibir retroalimentación inmediata sobre su código. La imagino más útil como herramienta del estudiante, pero bajo guía docente clara sobre cómo usarla correctamente.',
                'resp_cat3_p2' => 'Estaría dispuesto a adoptarla si es práctica, si no requiere demasiado tiempo de adaptación, y si está alineada con los objetivos del MEP. Lo que más resistencia me generaría es si implica que los estudiantes dependan de la IA para todo, o si la guía no está adaptada al nivel de secundaria técnica. Necesitaría ver evidencia de que funciona antes de comprometerme completamente.',
                'resp_cat3_p3' => 'La diferencia es enorme. El que pide código directamente obtiene una respuesta que no puede evaluar ni adaptar. El que pide que le expliquen el razonamiento de diseño está aprendiendo a pensar. He visto muy pocos estudiantes que usen la IA de esa segunda manera de forma espontánea, generalmente son los que ya tienen una base sólida. Es una habilidad que habría que enseñar explícitamente.',
                'resp_cat4_p1' => 'El acceso no es equitativo. Hay estudiantes de zonas rurales o con bajos recursos que solo tienen acceso a internet en la institución. En el aula contamos con computadoras, pero en casa muchos trabajan desde el celular con datos limitados. Esto genera una brecha real cuando se asignan tareas que requieren herramientas en línea fuera de clase.',
                'resp_cat4_p2' => 'He escuchado mencionar la Estrategia Nacional de IA del MEP pero no conozco los detalles de su implementación para 2026. En cuanto a capacitación institucional, hemos recibido algunos talleres generales sobre tecnología educativa, pero nada específico sobre IA generativa en programación. Básicamente cada docente ha tenido que aprender por su cuenta.',
                'resp_cierre'  => 'Creo que el tema más urgente es formar a los docentes primero, antes de pedirles que guíen a los estudiantes con IA. No se puede enseñar lo que no se sabe usar bien. Agradezco que se investigue esto desde el contexto costarricense.',
                'observaciones' => '',
            ],

            // ── D-02 · CTP · 3-7 años · entusiasta ──────────────────────────
            [
                'codigo_participante' => 'D-02',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'CTP Roberto Gamboa Valverde',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '3 a 7 años',
                'cursos_actuales'     => 'Programación I, Base de Datos, Soporte Técnico',
                'resp_cat1_p1' => 'La dificultad más común que veo es la abstracción. Pasar de "la computadora ejecuta instrucciones" a "los objetos tienen estado y comportamiento" es conceptualmente difícil. El bloqueo más frecuente es en el momento de instanciar objetos: los estudiantes confunden la clase con el objeto. Sí hay diferencia entre sintaxis y diseño: la sintaxis la aprenden relativamente rápido, pero diseñar un sistema coherente requiere una madurez conceptual que toma mucho más tiempo desarrollar.',
                'resp_cat1_p2' => 'Totalmente. La arquitectura por capas es el gran desafío de los cursos avanzados. Lo veo claramente en los proyectos finales: los estudiantes hacen consultas SQL directamente desde los eventos del formulario, sin ninguna capa intermedia. Creen que funciona porque el programa corre, pero sin comprender que el mantenimiento sería un desastre. El problema se hace evidente desde Programación II.',
                'resp_cat1_p3' => 'He adoptado una metodología de proyectos incrementales: empezamos con un sistema muy pequeño y lo vamos complejizando semana a semana, siempre refactorizando para separar capas. También funciona bien mostrarles código "malo" y pedirles que identifiquen qué está mal. Lo que menos ha funcionado es el enfoque teórico puro con UML antes de ver código real: los aburre y no conectan con la práctica.',
                'resp_cat2_p1' => 'Sí, constantemente. Desde que apareció ChatGPT el cambio fue inmediato y drástico. Lo usan principalmente para generar código de tareas, resolver ejercicios y copiar explicaciones. La mayoría lo hace de forma abierta, incluso me preguntan si pueden usarlo. En mi caso, lo permito con ciertas condiciones porque veo que tarde o temprano va a ser parte de su entorno laboral.',
                'resp_cat2_p2' => 'El problema principal es que el estudiante entrega código que no puede explicar. En evaluaciones orales colapsan. También he notado que cuando la IA genera código con un error, el estudiante no lo detecta porque no entiende el código. En cuanto a deshonestidad, es complicado probarlo, pero sí he tenido casos obvios donde el código supera con creces el nivel del estudiante.',
                'resp_cat2_p3' => 'No existe normativa formal en el CTP aún. Yo personalmente permito el uso de IA como herramienta de consulta, similar a cómo se permite buscar en Google. He ajustado mis evaluaciones para que incluyan explicaciones en vivo del código y resolución de problemas en tiempo real, donde la IA no puede ayudar directamente.',
                'resp_cat3_p1' => 'Completamente válido. Creo que la IA puede ser un tutor disponible las 24 horas, que explica conceptos de múltiples maneras sin cansarse. La veo útil para generar ejercicios adicionales personalizados, para explicar errores de compilación, y para ayudar a depurar. La imagino como herramienta de ambos: del estudiante para aprender y del docente para preparar material.',
                'resp_cat3_p2' => 'Sí, la adoptaría con gusto. Lo que necesitaría es que sea flexible, no prescriptiva — que sugiera prompts pero que me permita adaptarlos a mi contexto. Lo que me generaría resistencia es que sea demasiado rígida o que asuma que todos los estudiantes tienen acceso igual a internet.',
                'resp_cat3_p3' => 'Es una diferencia fundamental. El que pide el código tiene la solución pero no tiene conocimiento. El que pide el razonamiento tiene una conversación real de aprendizaje. Lamentablemente he visto muy pocos estudiantes que usen la IA de la segunda manera de forma espontánea. La mayoría va por el camino más corto. Por eso creo que hay que enseñarles explícitamente a formular buenas preguntas.',
                'resp_cat4_p1' => 'El acceso es bastante desigual. En el aula sí tenemos computadoras para todos, pero en casa la situación varía mucho. Algunos estudiantes viven en zonas sin internet de calidad. Cuando asigno tareas que requieren IA, siempre hago espacio dentro de la clase para quienes no tienen acceso en casa.',
                'resp_cat4_p2' => 'He leído algo sobre la Estrategia Nacional de IA del MEP, pero todavía no ha llegado de manera concreta a las aulas. No hemos recibido capacitación formal. Hemos aprendido explorando por nuestra cuenta, en grupos de WhatsApp con otros docentes, viendo tutoriales. Es un aprendizaje informal que debería ser institucionalizado.',
                'resp_cierre'  => 'Me parece muy valioso que se investigue esto desde una perspectiva pedagógica y no solo tecnológica. La pregunta importante no es si permitir la IA, sino cómo integrarla para que realmente apoye el aprendizaje. Espero que esta investigación genere recomendaciones prácticas para los docentes de programación.',
                'observaciones' => '',
            ],

            // ── D-03 · CTP · +15 años · crítico ─────────────────────────────
            [
                'codigo_participante' => 'D-03',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'CTP Roberto Gamboa Valverde',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => 'Más de 15 años',
                'cursos_actuales'     => 'Programación I, Programación II, Programación Avanzada, Proyecto Integrador',
                'resp_cat1_p1' => 'Con más de quince años enseñando, he visto que las dificultades fundamentales no cambian: la abstracción, el pensamiento lógico secuencial, y la capacidad de descomponer un problema complejo en partes manejables. Los estudiantes se bloquean principalmente en la fase de análisis, antes de escribir código. La diferencia entre aprender sintaxis y diseñar sistemas es que la primera es memorización y la segunda es comprensión profunda — y la escuela secundaria técnica generalmente entrena bien la primera pero tiene poco tiempo para la segunda.',
                'resp_cat1_p2' => 'Es el problema central de los últimos años del técnico. Los estudiantes entregan proyectos funcionales pero con arquitectura terrible. Todo en una clase, métodos de doscientas líneas, acceso directo a la base de datos desde la interfaz. Es una consecuencia directa de enseñar con ejemplos pequeños donde la arquitectura por capas parece innecesaria. El problema se hace crítico en el Proyecto Integrador de undécimo año.',
                'resp_cat1_p3' => 'Lo que mejor ha funcionado en mi experiencia es refactorizar código existente — tomar un proyecto funcional pero mal estructurado y mejorarlo juntos en clase. También funciona muy bien la revisión entre pares con rúbricas específicas de arquitectura. Lo que no funciona es la clase magistral sobre patrones de diseño sin un proyecto real de fondo: los estudiantes no ven para qué sirve.',
                'resp_cat2_p1' => 'Lo observo con mucha preocupación. Antes de la IA generativa, cuando un estudiante copiaba de internet, al menos el código que copiaba era de algún humano que lo había entendido. Ahora copian código generado que puede tener errores sutiles o que usa librerías que no conocemos en el CTP. La mayoría lo hace de forma disimulada aunque lo noto fácilmente por el cambio de estilo y vocabulario en el código.',
                'resp_cat2_p2' => 'Los problemas son varios. Primero, la incapacidad de depurar: si la IA generó el código y tiene un error, el estudiante no puede arreglarlo porque no lo entiende. Segundo, he tenido casos claros de proyectos completamente generados por IA que el estudiante no puede explicar. Tercero, me parece que estamos formando técnicos que van a depender de herramientas que no entienden, lo cual es peligroso en el mercado laboral.',
                'resp_cat2_p3' => 'No existe normativa formal. Yo la prohíbo en evaluaciones y lo explicito en el contrato pedagógico desde la primera semana. Sin embargo, reconozco que es difícil de controlar fuera del aula. He reforzado la evaluación oral y el trabajo en clase para reducir el impacto. Creo que la institución necesita definir una política clara al respecto.',
                'resp_cat3_p1' => 'Con cierta resistencia, reconozco que podría tener uso pedagógico si se usa correctamente. No la veo útil para generar código, pero sí para que el estudiante dialogue con ella sobre conceptos: preguntar por qué algo funciona de cierta manera, pedir alternativas, pedir que le explique un error. El riesgo es que los estudiantes tomen el camino corto y la usen como máquina de copiar.',
                'resp_cat3_p2' => 'Estaría dispuesto a considerarla si está muy bien estructurada y si hay evidencia de que mejora el aprendizaje real, no solo el rendimiento académico a corto plazo. Me generaría mucha resistencia si implica más trabajo para el docente sin apoyo institucional, o si sustituye el pensamiento propio del estudiante.',
                'resp_cat3_p3' => 'La diferencia es la diferencia entre aprender y hacer trampa. Quien pide el código no aprende. Quien pide el razonamiento tiene una oportunidad de aprender si realmente reflexiona sobre la respuesta. En 15 años de docencia he visto muy pocos estudiantes que naturalmente usen cualquier recurso de esa segunda manera — la mayoría busca la solución, no la comprensión. Eso es un problema de cultura educativa que va más allá de la IA.',
                'resp_cat4_p1' => 'La brecha digital existe y es real. Tenemos estudiantes de zonas rurales con acceso limitado en casa. En la institución contamos con laboratorio, pero los tiempos son limitados. Cuando diseño actividades con tecnología siempre debo pensar en la equidad de acceso, porque no puedo asumir que todos tienen computadora e internet en casa.',
                'resp_cat4_p2' => 'Tengo conocimiento general de los lineamientos del MEP sobre tecnología educativa, pero no conozco específicamente la Estrategia Nacional de IA 2026 en detalle. En cuanto a capacitación, hemos recibido talleres generales de tecnología educativa, pero nada específico sobre IA generativa. La capacitación que tengo sobre el tema la he conseguido por iniciativa propia.',
                'resp_cierre'  => 'Mi preocupación principal es que estamos tan enfocados en adaptar la educación a la IA que olvidamos preguntarnos si esa adaptación realmente beneficia al estudiante a largo plazo. La capacidad de resolver problemas sin depender de herramientas externas es una competencia que el mercado laboral siempre va a valorar, independientemente de qué herramientas existan. No debemos sacrificar eso.',
                'observaciones' => '',
            ],

            // ── D-04 · Universidad · 8-15 años · pragmático ─────────────────
            [
                'codigo_participante' => 'D-04',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'Universidad Latina de Costa Rica',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '8 a 15 años',
                'cursos_actuales'     => 'Programación Orientada a Objetos, Arquitectura de Software, Taller de Proyectos',
                'resp_cat1_p1' => 'En el contexto universitario, la dificultad más profunda que encuentro es la transición del código que "funciona" al código que es correcto, mantenible y escalable. Los estudiantes de primer año llegan con la mentalidad de que si el programa corre, está bien. El bloqueo más crítico ocurre cuando tienen que integrar múltiples clases en un sistema cohesivo — el diseño holístico es lo más difícil. La diferencia entre sintaxis y diseño de sistemas es que la primera es una herramienta y la segunda es un arte que toma años desarrollar.',
                'resp_cat1_p2' => 'Es un problema recurrente en POO y en Arquitectura. Los estudiantes llegan a la universidad sin haber trabajado con capas. En el código que entregan predominan las clases "Dios" que hacen todo, la lógica de negocio mezclada con la interfaz, y el acceso directo a datos desde cualquier parte del sistema. La dificultad se hace más visible en los cursos de II y III año cuando los proyectos crecen en complejidad.',
                'resp_cat1_p3' => 'El enfoque que mejores resultados me ha dado es el aprendizaje basado en revisión de código de proyectos reales — repositorios de código abierto. Los estudiantes ven cómo se estructura código profesional antes de intentarlo ellos mismos. También funciona bien asignar roles dentro del equipo (arquitecto, desarrollador, tester) para que entiendan las responsabilidades separadas. Lo que no funciona es el análisis teórico de patrones sin aplicación inmediata.',
                'resp_cat2_p1' => 'Es muy frecuente y bastante abierto en la universidad. Los estudiantes universitarios, en general, no tienen vergüenza de admitir que usan ChatGPT o Claude. Lo usan para tareas, proyectos, y también para estudiar para los exámenes. Lo noto principalmente en el estilo del código — más idiomático de lo que corresponde a su nivel — y en los comentarios que explican perfectamente el código pero que el estudiante no puede parafrasear en persona.',
                'resp_cat2_p2' => 'El problema principal es la ilusión de comprensión: el estudiante cree que entiende porque tiene el código funcionando, pero cuando cambio una variable del problema en el examen, no puede adaptar la solución. He tenido casos de deshonestidad académica donde proyectos completos fueron generados por IA. Noto diferencia clara en los exámenes presenciales entre estudiantes que trabajan con IA de manera reflexiva y los que simplemente copian.',
                'resp_cat2_p3' => 'En la Universidad Latina tenemos un reglamento de integridad académica que menciona el uso de IA pero de manera general. A nivel de curso, yo permito el uso de IA como recurso de apoyo, pero en las entregas se debe documentar qué se usó y cómo. He modificado mis evaluaciones para incluir más componentes de presentación oral y resolución de problemas en tiempo real que no se pueden preparar con IA.',
                'resp_cat3_p1' => 'Absolutamente sí. La IA tiene un potencial enorme en la enseñanza de programación, especialmente para retroalimentación inmediata. Un estudiante a las 11 de la noche depurando un error no tiene acceso al docente, pero sí tiene acceso a la IA. La veo útil para ambos: para el estudiante como tutor disponible siempre, y para el docente para generar material didáctico diferenciado. El uso más valioso que imagino es como interlocutor de diseño: que el estudiante le explique su diseño a la IA y la IA le haga preguntas.',
                'resp_cat3_p2' => 'Sí, la adoptaría. Las condiciones serían que sea práctica, que esté basada en evidencia, y que tenga ejemplos concretos por tipo de actividad. Lo que más resistencia me generaría es si implica mucho tiempo adicional de preparación o si siento que la guía dicta cómo debo enseñar en lugar de apoyar mi práctica existente.',
                'resp_cat3_p3' => 'Es la diferencia entre usar una calculadora para verificar un resultado que ya calculaste, versus usar la calculadora sin saber hacer la operación. El estudiante que pide razonamiento está aprendiendo a pensar; el que pide código está tercializando el pensamiento. He visto algunos estudiantes avanzados usar la IA de manera sofisticada — como interlocutor para validar decisiones de diseño — pero son excepciones, no la norma.',
                'resp_cat4_p1' => 'En el contexto universitario el acceso es generalmente mejor que en secundaria, pero no es uniforme. Hay estudiantes que trabajan y estudian, que tienen recursos limitados, o que viven lejos de la universidad. Diría que la brecha en universidad es más de tiempo que de infraestructura: algunos estudiantes simplemente no tienen tiempo para explorar herramientas nuevas.',
                'resp_cat4_p2' => 'Conozco de forma general la Estrategia Nacional de IA del MEP, aunque no todos sus detalles. En la Universidad Latina hemos tenido algunas charlas informativas sobre IA y educación, pero no una capacitación estructurada sobre cómo integrarla pedagógicamente. La mayoría del conocimiento que tengo lo he desarrollado de forma autodidacta y compartiéndolo con colegas.',
                'resp_cierre'  => 'Me interesa destacar que la pregunta clave no es tecnológica sino pedagógica: ¿qué queremos que nuestros estudiantes aprendan a hacer por sí mismos? Una vez que tengamos claridad sobre eso, podremos definir dónde la IA ayuda y dónde obstaculiza. Esa claridad de objetivos de aprendizaje tiene que venir primero.',
                'observaciones' => '',
            ],

            // ── D-05 · Universidad · 3-7 años · innovador ───────────────────
            [
                'codigo_participante' => 'D-05',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'Universidad Latina de Costa Rica',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '3 a 7 años',
                'cursos_actuales'     => 'Fundamentos de Programación, Estructuras de Datos, Desarrollo Web',
                'resp_cat1_p1' => 'Como docente relativamente nuevo, lo que más me impacta es que los estudiantes llegan con una expectativa de que programar es "teclear" y que si el IDE no subraya nada en rojo, está bien. La abstracción — entender que el código es una representación de una solución a un problema real — es lo más difícil de transmitir. El bloqueo más frecuente es en el momento de plantear el problema antes de codificar. La diferencia entre sintaxis y diseño es que una se aprende en días y el otro se desarrolla con años de práctica reflexiva.',
                'resp_cat1_p2' => 'Sí, es un problema que aparece desde Estructuras de Datos y se profundiza en los cursos avanzados. Los estudiantes tienden a poner toda la lógica en el método main o en la interfaz de usuario. Cuando intento explicar por qué separar capas, la respuesta típica es "pero funciona igual". El reto pedagógico es hacerles ver que la arquitectura no es para hoy sino para el mantenimiento futuro.',
                'resp_cat1_p3' => 'He tenido buenos resultados con el "refactoring en vivo" durante la clase: tomo código que funciona pero está mal estructurado y lo mejoramos juntos, discutiendo cada decisión. También funciona bien conectar los conceptos con situaciones laborales reales — cuando les digo que en la empresa van a heredar código horrible y tendrán que entenderlo, prestan más atención al diseño. Los proyectos aislados sin continuidad no funcionan bien para enseñar arquitectura.',
                'resp_cat2_p1' => 'Es una realidad cotidiana. Los estudiantes de mi generación son nativos digitales y adoptan cualquier herramienta nueva inmediatamente. Lo usan abiertamente y yo lo facilito dentro de ciertos límites. Lo noto principalmente en la calidad del código que entregan versus la calidad de lo que hacen en clase: la brecha es grande cuando usan IA sin comprensión.',
                'resp_cat2_p2' => 'El problema más grave que he observado es la incapacidad de iterar: cuando la solución generada por IA no resuelve exactamente el problema, el estudiante no sabe cómo ajustarla. También he notado que los estudiantes que usan IA para generar código tienen dificultad mayor en los exámenes presenciales. En cuanto a deshonestidad, he tenido casos, pero prefiero rediseñar las evaluaciones para hacerlas más difíciles de resolver con IA que gastar energía en detectar y sancionar.',
                'resp_cat2_p3' => 'En mi materia permito el uso de IA con documentación explícita del proceso: el estudiante debe mostrar la conversación que tuvo con la IA, justificar las decisiones que tomó y explicar qué modificó. Esto transforma el uso de IA de una trampa en un proceso de aprendizaje documentado. La universidad no tiene todavía una política clara y unificada.',
                'resp_cat3_p1' => 'Creo que es una de las herramientas más poderosas que ha llegado a la educación en décadas, si se usa bien. La imagino muy útil para tutorías personalizadas, para generar variaciones de ejercicios, para explicar errores en lenguaje natural, y para que el estudiante practique la habilidad de formular preguntas precisas. La veo como herramienta principalmente del estudiante, pero con mediación pedagógica del docente.',
                'resp_cat3_p2' => 'La adoptaría con entusiasmo. Lo que necesitaría es que sea colaborativa — que los docentes podamos sugerir ajustes según nuestra experiencia — y que tenga ejemplos muy concretos y listos para usar. Lo que más resistencia me generaría es si la guía asume acceso tecnológico uniforme o si no considera las diferencias de contexto socioeconómico de nuestros estudiantes.',
                'resp_cat3_p3' => 'Es la diferencia entre consumir y aprender. Quien pide el código obtiene un resultado; quien pide el razonamiento desarrolla una competencia. He visto algunos estudiantes avanzados usar la IA de esa segunda manera, pero son pocos. Creo que es una habilidad metacognitiva que hay que enseñar deliberadamente — no surge sola. Es parte de lo que me parece más valioso de esta investigación: visibilizar esa diferencia.',
                'resp_cat4_p1' => 'El acceso en la universidad es relativamente bueno comparado con secundaria, pero hay estudiantes que trabajan tiempo completo y estudian de noche, con acceso limitado. La universidad tiene wifi en campus pero no todos los estudiantes pueden estar en campus regularmente. Cuando diseño actividades digitales siempre ofrezco alternativas para quienes tienen restricciones de acceso.',
                'resp_cat4_p2' => 'Conozco la existencia de la Estrategia Nacional de IA del MEP aunque no todos los detalles de implementación. En la Universidad Latina hemos tenido algunas sesiones informativas pero no capacitación pedagógica profunda sobre cómo integrar IA en el aula. Como docente relativamente joven, he explorado mucho por mi cuenta y creo que eso me pone en ventaja, pero no debería ser solo responsabilidad individual.',
                'resp_cierre'  => 'Me gustaría que esta investigación visibilice que el problema no es la IA en sí, sino la falta de marcos pedagógicos para integrarla. Los docentes necesitamos orientación práctica, no prohibiciones ni adopción ciega. Un conjunto de guías de prompts para enseñanza de programación sería un aporte muy concreto y valioso.',
                'observaciones' => '',
            ],

            // ── D-06 · Universidad · +15 años · reflexivo ───────────────────
            [
                'codigo_participante' => 'D-06',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'Universidad Latina de Costa Rica',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => 'Más de 15 años',
                'cursos_actuales'     => 'Programación Orientada a Objetos, Ingeniería de Software, Seminario de Investigación',
                'resp_cat1_p1' => 'Con quince años de experiencia universitaria, puedo afirmar que las dificultades fundamentales son constantes aunque el contexto cambie. La más persistente es la incapacidad de pensar en términos de responsabilidades: qué sabe cada componente y qué no debe saber. Los estudiantes se bloquean principalmente cuando tienen que tomar decisiones de diseño sin una respuesta "correcta" única. La brecha entre sintaxis y diseño de sistemas refleja la brecha entre saber hacer y saber pensar — la educación técnica tiende a desarrollar bien la primera y descuidar la segunda.',
                'resp_cat1_p2' => 'Es quizá el indicador más claro del nivel de madurez del estudiante como programador. En 15 años he visto la misma progresión: el estudiante aprende a hacer programas que funcionan, luego aprende a hacer programas que están bien estructurados, y finalmente aprende a hacer sistemas que otros pueden mantener. La mayoría de los estudiantes universitarios está en la primera etapa cuando deberían estar avanzando hacia la segunda. La arquitectura por capas requiere que primero entiendan por qué existe, no solo cómo implementarla.',
                'resp_cat1_p3' => 'A lo largo de los años he llegado a la conclusión de que el aprendizaje de diseño requiere práctica deliberada con retroalimentación experta. Lo que mejor funciona es la mentoría de código: revisiones frecuentes y conversacionales donde el estudiante justifica sus decisiones y yo las cuestiono. Los proyectos largos con hitos de revisión funcionan mucho mejor que los proyectos cortos sin revisión. Lo que no funciona es la exposición de reglas sin práctica: los estudiantes pueden recitar los principios SOLID y violarlos todos en el mismo proyecto.',
                'resp_cat2_p1' => 'Lo observo como un cambio estructural en la dinámica del curso, no como un evento aislado. Desde 2023 la forma en que los estudiantes abordan las tareas cambió notablemente. Ahora llegan a clase con código funcionando que no entienden, en lugar de llegar con código roto que intentaron resolver. La segunda situación es pedagógicamente más valiosa. Lo hacen mayoritariamente de forma abierta, porque la cultura universitaria actual lo normaliza.',
                'resp_cat2_p2' => 'El impacto más profundo que he observado es en la capacidad de resolución de problemas nuevos. Los estudiantes que usan la IA de forma acrítica tienen mayor dificultad para resolver problemas en contextos ligeramente diferentes a los del ejemplo. También he notado una disminución en la tolerancia a la frustración: si la IA no resuelve el problema en el primer intento, el estudiante se desespera en lugar de reflexionar. En cuanto a deshonestidad, prefiero transformar las evaluaciones que perseguir casos individuales.',
                'resp_cat2_p3' => 'En la Universidad Latina existe un reglamento de integridad académica actualizado en 2024 que incluye referencias al uso de IA, aunque de manera general. A nivel de carrera no hay política unificada todavía. Yo adopté hace dos años una política de transparencia: uso de IA permitido y documentado, con reflexión explícita sobre el proceso. Ha funcionado mejor que la prohibición, que era imposible de controlar.',
                'resp_cat3_p1' => 'Después de reflexionar mucho, sí creo que tiene potencial pedagógico real, pero requiere un diseño instruccional cuidadoso. La imagino más útil como herramienta socrática: que el estudiante la use para explorar, para hacerse preguntas, para validar su razonamiento — no para obtener respuestas. La veo como herramienta principalmente del estudiante, pero el docente tiene que diseñar las actividades que enmarquen ese uso de manera que propicie el aprendizaje real.',
                'resp_cat3_p2' => 'Sí, estaría dispuesto, con las condiciones adecuadas. Necesitaría que la guía sea fundamentada pedagógicamente, no solo tecnológicamente. Que explique el por qué de cada tipo de prompt, no solo el cómo. Lo que me generaría resistencia es si la guía está diseñada para docentes sin considerar las diferencias entre niveles educativos, disciplinas o contextos institucionales. Una guía para secundaria técnica y una para universidad tienen que ser distintas.',
                'resp_cat3_p3' => 'Es una distinción fundamental y muy poco explorada pedagógicamente. Quien pide el código está en una relación de dependencia con la herramienta. Quien pide el razonamiento está en una relación de diálogo epistémico — usa la IA como interlocutor para construir conocimiento. He visto eso muy pocas veces de forma espontánea, solo en estudiantes avanzados y curiosos. Enseñar a hacer esa segunda cosa debería ser uno de los objetivos centrales de cualquier guía pedagógica de uso de IA.',
                'resp_cat4_p1' => 'La inequidad de acceso es real incluso en la universidad privada. Hay estudiantes con recursos limitados, que trabajan, que no tienen computadora propia de calidad. En mis cursos siempre ofrezco alternativas para quienes tienen limitaciones, y trato de no diseñar actividades que requieran tecnología de alto costo o conexión permanente. La equidad de acceso es una consideración ética que no podemos ignorar.',
                'resp_cat4_p2' => 'Conozco bien la Estrategia Nacional de IA del MEP 2026 y he seguido su desarrollo. En la Universidad hemos tenido algunas jornadas de sensibilización, pero no capacitación pedagógica profunda. He participado en algunos espacios de formación externos por iniciativa propia. Creo que las universidades privadas en Costa Rica tienen un rezago importante en la preparación de sus docentes para integrar IA de manera pedagógicamente responsable.',
                'resp_cierre'  => 'Me parece fundamental que la investigación en este campo no se limite a describir el uso actual de la IA, sino que proponga marcos de acción concretos para los docentes. La pregunta relevante no es si los estudiantes usan IA — la usan y la usarán — sino cómo diseñamos experiencias de aprendizaje que hagan que ese uso sea genuinamente formativo y no una forma sofisticada de evadir el aprendizaje. Esa es la pregunta que su investigación está tratando de responder y me parece muy oportuna.',
                'observaciones' => '',
            ],

        ];

        foreach ($docentes as $data) {
            Entrevista::firstOrCreate(['codigo_participante' => $data['codigo_participante']], $data);
        }

        $docentes2 = [

            // ── D-07 · CTP · 3-7 años · neutral, enfocada en evaluación ─────
            [
                'codigo_participante' => 'D-07',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'CTP Roberto Gamboa Valverde',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '3 a 7 años',
                'cursos_actuales'     => 'Programación I, Diseño Gráfico Digital, Mantenimiento de Equipos',
                'resp_cat1_p1' => 'En mi experiencia en el CTP, la dificultad más grande es que los estudiantes asocian programar con escribir código y no con resolver problemas. Cuando se les plantea un problema sin un ejemplo previo idéntico, se paralizan. El bloqueo más frecuente lo noto en la etapa de análisis: no saben por dónde empezar si no tienen un molde que seguir. La diferencia entre sintaxis y diseño es que la sintaxis tiene respuestas correctas claras, mientras que el diseño requiere justificar decisiones — y eso los pone muy incómodos.',
                'resp_cat1_p2' => 'Sí, es algo que veo especialmente en Programación II. Los estudiantes mezclan todo en el mismo archivo o en la misma clase. No tienen el hábito de pensar en quién es responsable de qué. Lo interesante es que cuando les explico que la separación de capas es para que otro programador pueda entender el código, comienzan a entenderlo mejor — se vuelve un problema humano, no solo técnico.',
                'resp_cat1_p3' => 'He tenido buenos resultados con lo que llamo "programación narrada": les pido que antes de escribir código, me digan en voz alta qué va a hacer cada clase y por qué. Si no pueden explicarlo, entonces no pueden programarlo. También funciona el trabajo en parejas donde uno programa y el otro solo pregunta "¿por qué?" a cada decisión. Lo que no ha funcionado son los libros de texto — en secundaria técnica el contexto tiene que ser muy concreto.',
                'resp_cat2_p1' => 'Sí, y el cambio fue muy notorio a partir de 2023. Lo usan principalmente para tareas y para resolver ejercicios de práctica. Muchos lo admiten abiertamente cuando les pregunto. Lo interesante es que algunos estudiantes me han mostrado cómo usan el chat para pedir que les expliquen un error — eso me parece un uso válido. El problema es cuando simplemente copian la respuesta sin leerla.',
                'resp_cat2_p2' => 'El problema más concreto que he visto es que los estudiantes no pueden modificar el código que la IA les generó. Si cambio un detalle del problema en el examen, no saben adaptar la solución. También he notado que el código generado por IA a veces incluye librerías o patrones que están fuera del nivel del curso, lo que hace evidente que no fue el estudiante quien lo escribió. No he llevado casos formales de deshonestidad, pero sí he anulado entregas donde era obvio.',
                'resp_cat2_p3' => 'En el CTP no hay una política institucional clara sobre el uso de IA todavía. Cada docente maneja el tema a su criterio. Yo he optado por permiten con registro: si el estudiante usó IA, debe indicarlo y explicar qué modificó. Esto transforma el uso en algo más reflexivo. He cambiado mis evaluaciones para incluir más componentes de demostración en vivo.',
                'resp_cat3_p1' => 'Creo que sí tiene potencial, sobre todo para resolver dudas rápidas fuera del horario de clases. En secundaria técnica el docente no siempre está disponible cuando el estudiante está trabajando en su proyecto en la noche. En ese contexto, tener una herramienta que le explique un error en lenguaje natural es muy valioso. La veo más como herramienta del estudiante que del docente, aunque también podría ayudarme a preparar material.',
                'resp_cat3_p2' => 'Sí, la adoptaría. Lo que necesito es que sea práctica y que pueda integrarla sin cambiar completamente mi metodología actual. Lo que más resistencia me generaría es si requiere que los estudiantes tengan acceso constante a internet fuera del aula, porque no todos lo tienen. La guía tendría que considerar la realidad del contexto técnico costarricense.',
                'resp_cat3_p3' => 'La diferencia es fundamental: uno está ejecutando y el otro está aprendiendo. El que pide código es como el que copia la tarea — tiene el resultado sin el proceso. El que pide razonamiento está haciendo algo parecido a preguntar a un tutor. He visto muy pocos estudiantes que usen la IA de esa segunda manera espontáneamente, generalmente son los más motivados. Eso refuerza mi idea de que habría que enseñarlo explícitamente.',
                'resp_cat4_p1' => 'El acceso en el CTP es razonablemente bueno dentro de la institución — tenemos laboratorio — pero fuera de ella es muy variable. Hay estudiantes que vienen de zonas rurales o de familias de bajos recursos que solo tienen acceso a internet a través del celular. Diseñar actividades con IA que requieran computadora y conexión estable fuera del aula los excluiría.',
                'resp_cat4_p2' => 'He escuchado mencionar la Estrategia Nacional de IA del MEP pero no he recibido información detallada de cómo se va a implementar en los colegios técnicos. No hemos tenido capacitación específica. Lo que sé del tema lo he aprendido por cuenta propia, principalmente buscando recursos en línea y conversando con colegas de otras instituciones.',
                'resp_cierre'  => 'Me gustaría que cualquier guía que resulte de esta investigación sea muy concreta y aplicable en el contexto de secundaria técnica, no solo en universidad. Los colegios técnicos tienen una realidad muy particular — estudiantes con contextos socioeconómicos diversos, acceso variable a tecnología, y una tradición pedagógica muy orientada a la práctica inmediata.',
                'observaciones' => '',
            ],

            // ── D-08 · CTP · menos de 3 años · nativo digital, abierto ──────
            [
                'codigo_participante' => 'D-08',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'CTP Roberto Gamboa Valverde',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => 'Menos de 3 años',
                'cursos_actuales'     => 'Programación I, Aplicaciones Móviles',
                'resp_cat1_p1' => 'Soy docente de primera generación, como ellos. Lo que más me cuesta enseñar es la lógica de descomposición de problemas: los estudiantes quieren ir directo al código sin pensar el problema primero. El bloqueo más frecuente que veo es cuando no hay un ejemplo que copiar — ahí se paralizan completamente. Noto que aprenden la sintaxis con relativa facilidad porque hay muchos recursos en línea, pero el diseño de sistemas es algo que no encuentran fácilmente en YouTube y requiere acompañamiento humano.',
                'resp_cat1_p2' => 'Sí, es evidente en los proyectos de fin de semestre. El código funciona pero es un bloque monolítico. Cuando les pregunto por qué pusieron todo en una clase, la respuesta típica es que "era más fácil". El concepto de arquitectura por capas todavía lo estoy aprendiendo a enseñar — es el tema que más me ha retado en este primer año y medio de docencia.',
                'resp_cat1_p3' => 'Lo que más me ha funcionado es mostrarles código mío — de proyectos reales en los que he trabajado — y explicarles las decisiones que tomé. Que vean al docente programar en tiempo real hace que el proceso sea más tangible. Lo que menos ha funcionado es la teoría abstracta de clases y objetos sin un ejemplo de negocio concreto.',
                'resp_cat2_p1' => 'Completamente cotidiano. Yo mismo uso IA en mi trabajo y no veo por qué ocultarlo. Lo que intento hacer es modelar el uso correcto: en clase a veces uso la IA en el proyector para resolver algo juntos, y les muestro cómo evaluar y cuestionar la respuesta que da. Creo que si voy a competir con una herramienta que responde en segundos, tengo que ofrecer algo que la IA no puede: contexto, criterio y acompañamiento humano.',
                'resp_cat2_p2' => 'El problema principal es que los estudiantes no desarrollan la tolerancia al error que es fundamental en programación. La IA les da una solución inmediata y se saltean el proceso de depuración que es donde más se aprende. En cuanto a deshonestidad, prefiero diseñar tareas que sean difíciles de resolver con IA — que requieran aplicar el contexto específico del curso — en lugar de prohibirla.',
                'resp_cat2_p3' => 'En el CTP no hay norma todavía. Yo la permito libremente pero hago hincapié en que el examen es sin IA y que lo que no entienden se nota ahí. No he modificado significativamente las evaluaciones porque llevo poco tiempo, pero sí he empezado a incluir más preguntas de razonamiento oral.',
                'resp_cat3_p1' => 'Totalmente válido. Creo que la IA es una herramienta más, como lo fue el debugger o Stack Overflow en su momento. Lo que cambia es la velocidad y la accesibilidad. La imagino muy útil para que los estudiantes practiquen conceptos fuera de clase — pueden preguntarle a la IA, recibir explicación, intentarlo, equivocarse y volver a preguntar en un ciclo de práctica que antes requería al docente presente. La veo como herramienta de ambos.',
                'resp_cat3_p2' => 'La adoptaría con mucho gusto. Necesitaría que sea compatible con el nivel de secundaria técnica y que tenga ejemplos con el tipo de proyectos que hacemos aquí. Lo que me generaría resistencia es si la guía asume que todos los docentes tienen el mismo nivel de familiaridad con la IA — yo puede que tenga más que algunos colegas con más experiencia, y eso hay que considerarlo.',
                'resp_cat3_p3' => 'El que pide código tiene una respuesta; el que pide razonamiento tiene una conversación de aprendizaje. Es la diferencia entre Google y un tutor. He visto algunos estudiantes que naturalmente hacen buenas preguntas a la IA — son los mismos que hacen buenas preguntas en clase. Es una competencia cognitiva que está relacionada con la curiosidad y el pensamiento crítico, no solo con la IA.',
                'resp_cat4_p1' => 'El acceso en la institución es bueno, pero fuera del aula hay estudiantes con limitaciones serias. Tenemos casos de estudiantes que hacen tareas desde el celular porque no tienen computadora en casa. Cuando asigno actividades con IA siempre reservo tiempo en el laboratorio para que quienes no tienen acceso en casa puedan completarlas dentro de la institución.',
                'resp_cat4_p2' => 'Tengo conocimiento general de los lineamientos del MEP sobre tecnología educativa. No he recibido capacitación formal sobre IA en la institución, pero como soy relativamente joven y uso mucho la tecnología, he aprendido bastante por mi cuenta. Me gustaría que hubiera más espacio institucional para compartir estas experiencias entre docentes.',
                'resp_cierre'  => 'Como docente nuevo, me parece que esta investigación llega en un momento clave. Estamos en una encrucijada: podemos prohibir la IA y perder credibilidad ante los estudiantes, o podemos integrarla de forma inteligente y enseñarles a usarla como profesionales. La segunda opción es la correcta, pero necesitamos orientación para hacerlo bien.',
                'observaciones' => '',
            ],

            // ── D-09 · CTP · 8-15 años · preocupada por brecha digital ──────
            [
                'codigo_participante' => 'D-09',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'CTP Roberto Gamboa Valverde',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '8 a 15 años',
                'cursos_actuales'     => 'Programación II, Redes de Computadoras, Electrónica Digital',
                'resp_cat1_p1' => 'La dificultad que más me preocupa es la falta de pensamiento algorítmico previo. Los estudiantes del CTP llegan muchas veces sin haber tenido exposición suficiente a la lógica de resolución de problemas. El bloqueo más frecuente es precisamente al inicio, cuando tienen que analizar un problema antes de codificarlo. La diferencia entre aprender sintaxis y diseñar sistemas es similar a la diferencia entre aprender vocabulario y escribir un ensayo — una es condición necesaria pero no suficiente para la otra.',
                'resp_cat1_p2' => 'Sí, es un problema real. Pero también entiendo que en el contexto del CTP, con los tiempos curriculares que tenemos, es difícil llegar a los niveles de abstracción que requiere la arquitectura por capas con profundidad. El problema se manifiesta cuando los proyectos crecen: el código que funcionaba a pequeña escala se vuelve inmanejable. Es desde undécimo año donde esto se hace más crítico.',
                'resp_cat1_p3' => 'He tenido buenos resultados con proyectos basados en problemas reales del contexto local de los estudiantes — aplicaciones que les resuelvan algo a ellos o a su comunidad. Cuando hay motivación intrínseca, la disposición a aprender el diseño correcto aumenta. Lo que no ha funcionado bien son los proyectos genéricos de "sistema de inventario" que no les interesan. La motivación importa mucho en el aprendizaje del diseño.',
                'resp_cat2_p1' => 'Lo observo, aunque con una particularidad importante: no todos mis estudiantes tienen acceso equitativo a estas herramientas. Los estudiantes de zonas rurales o sin internet de calidad en casa tienen mucho menos uso de IA que sus compañeros con mejor conectividad. Esto crea una brecha adicional que me preocupa. Los que sí la usan lo hacen principalmente para tareas y lo admiten sin problema.',
                'resp_cat2_p2' => 'Además de los problemas de comprensión superficial que son comunes, me preocupa el impacto en la equidad: los estudiantes con mejor acceso a IA de calidad pueden tener ventajas sobre los que no tienen. He observado que las diferencias de rendimiento entre estudiantes con y sin acceso tecnológico en casa se han ampliado desde que la IA generativa se popularizó. Eso es un problema de justicia educativa.',
                'resp_cat2_p3' => 'No hay normativa institucional específica. Yo tengo una postura pragmática: no puedo prohibir lo que no puedo controlar fuera del aula, y dentro del aula estamos en el laboratorio donde puedo orientar mejor el uso. He modificado mis evaluaciones para que sean principalmente presenciales y con explicación oral.',
                'resp_cat3_p1' => 'Potencial sí tiene, pero me preocupa que su integración en la educación pueda profundizar las brechas existentes si no se maneja con cuidado. Si la IA es una herramienta que beneficia principalmente a quienes ya tienen más acceso y recursos, entonces su uso en la educación puede ser contraproducente desde una perspectiva de equidad. Eso es algo que cualquier propuesta pedagógica de uso de IA debe considerar seriamente.',
                'resp_cat3_p2' => 'Estaría dispuesta a adoptarla si incluye consideraciones explícitas de equidad de acceso — si la guía contempla qué hacer cuando no todos los estudiantes tienen acceso en casa. Lo que más resistencia me generaría es una guía que asuma conectividad universal o que ignore el contexto socioeconómico del estudiantado de secundaria técnica pública.',
                'resp_cat3_p3' => 'La diferencia es enorme pedagógicamente. El que pide razonamiento está en una relación activa con el conocimiento; el que pide código está en una relación pasiva. Pero hay que considerar también que pedir razonamiento efectivamente requiere saber hacer buenas preguntas, y eso es una competencia que también se debe enseñar. He visto muy pocos estudiantes que lo hagan espontáneamente.',
                'resp_cat4_p1' => 'Es la dimensión que más me preocupa de todo este tema. En mi experiencia, la brecha digital en el CTP es significativa. Tenemos estudiantes de zonas rurales, de familias numerosas con un solo dispositivo para toda la familia, o que deben compartir el celular con sus padres. Cualquier propuesta de integración de IA en el aula tiene que partir de esa realidad, no de la realidad de los estudiantes universitarios de la capital.',
                'resp_cat4_p2' => 'Conozco en términos generales la Estrategia Nacional de IA del MEP pero no he recibido capacitación institucional específica. Lo que más me interesaría recibir no es capacitación técnica sobre cómo usar la IA, sino orientación pedagógica sobre cómo integrarla de manera equitativa en contextos con acceso desigual.',
                'resp_cierre'  => 'Mi mensaje principal es que cualquier propuesta de integración de IA en la enseñanza de programación debe tener la equidad como principio rector. La tecnología puede amplificar tanto el aprendizaje como las brechas existentes. El contexto del CTP es muy diferente al universitario y merece investigación y propuestas específicas.',
                'observaciones' => '',
            ],

            // ── D-10 · Universidad · menos de 3 años · muy tech-forward ──────
            [
                'codigo_participante' => 'D-10',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'Universidad Latina de Costa Rica',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => 'Menos de 3 años',
                'cursos_actuales'     => 'Programación Orientada a Objetos, Introducción a la Inteligencia Artificial, Taller de Software',
                'resp_cat1_p1' => 'Vengo de la industria y llevo dos años en docencia. Lo que más me sorprendió al entrar al aula fue que los estudiantes tienen dificultad no solo con los conceptos de programación sino con el pensamiento sistémico en general. La dificultad más frecuente es entender que un programa es un modelo de algo del mundo real — esa abstracción de que el código representa entidades con propiedades y comportamientos. El bloqueo ocurre cuando tienen que tomar decisiones de diseño sin que haya una respuesta única correcta; eso los desestabiliza.',
                'resp_cat1_p2' => 'Constantemente. El problema es que en los recursos de aprendizaje en línea que más consumen — tutoriales de YouTube, Stack Overflow, GitHub — el código está generalmente en un solo archivo o mal estructurado por simplicidad pedagógica. Están aprendiendo malos hábitos de las mismas fuentes que usan para aprender. La arquitectura por capas requiere un esfuerzo pedagógico deliberado porque va contra los ejemplos más accesibles.',
                'resp_cat1_p3' => 'Lo que mejor me ha funcionado es conectar el diseño con la experiencia de mantenimiento: les pido que tomen código de un proyecto anterior — del semestre pasado — e intenten agregar una funcionalidad nueva. Cuando ven lo difícil que es modificar código mal estructurado, entienden por qué la arquitectura importa. También funciona bien usar GitHub con historial de commits para que vean cómo evoluciona el código a lo largo del tiempo.',
                'resp_cat2_p1' => 'Es prácticamente universal en mis grupos. Yo mismo lo uso profesionalmente, así que no tengo ningún problema con eso. Lo que hago es incorporarlo explícitamente en el curso: hay actividades donde el uso de IA está definido y es parte del proceso de aprendizaje. Los estudiantes lo usan principalmente para generar código base, explicar errores, y resumir documentación técnica. La transparencia sobre el uso es lo que más fomento.',
                'resp_cat2_p2' => 'El problema principal no es la deshonestidad sino la falta de pensamiento crítico sobre las respuestas de la IA. Los estudiantes aceptan lo que la IA dice sin cuestionarlo, incluso cuando está incorrecto. He visto código con bugs generados por IA que el estudiante entregó sin probar. Eso revela una comprensión muy superficial. En la industria, un programador que no verifica el código que usa — sea de IA o de cualquier fuente — es un riesgo.',
                'resp_cat2_p3' => 'En la Universidad Latina hay un reglamento actualizado que menciona la IA, pero la implementación práctica queda a criterio de cada docente. Yo tengo una política de uso abierto con documentación del proceso de IA y reflexión sobre las decisiones tomadas. He rediseñado los proyectos para que sean tan específicos al contexto del curso que sea difícil resolverlos con IA sin entender primero los conceptos.',
                'resp_cat3_p1' => 'Completamente. Creo que la IA generativa va a ser tan fundamental en el desarrollo de software como lo fue el IDE o el control de versiones. La pregunta no es si usarla sino cómo enseñar a usarla profesionalmente. La imagino útil para acelerar el ciclo de aprendizaje: probar ideas más rápido, obtener retroalimentación inmediata, explorar alternativas de diseño. La veo como herramienta de ambos, estudiante y docente.',
                'resp_cat3_p2' => 'La adoptaría inmediatamente. Lo único que necesito es que esté basada en evidencia pedagógica real, no solo en intuición. Lo que me generaría resistencia es si la guía es prescriptiva y no permite adaptación — cada curso, cada grupo y cada docente tiene un contexto diferente y la guía debería ser un marco flexible, no un manual rígido.',
                'resp_cat3_p3' => 'Es la diferencia entre un junior que usa Stack Overflow para copiar y uno que lo usa para aprender el patrón. En la industria, la segunda manera es lo que distingue a alguien que crece de alguien que se estanca. He visto algunos estudiantes de últimos años que usan la IA de forma muy sofisticada — como compañero de revisión de código — y eso es exactamente el perfil que necesita el mercado laboral costarricense.',
                'resp_cat4_p1' => 'En el contexto universitario el acceso es generalmente mejor, pero hay disparidades. Los estudiantes que trabajan tiempo completo tienen limitaciones de tiempo más que de acceso. En mi caso, diseño actividades que se puedan hacer asíncronamente y con tiempos flexibles para acomodar esa realidad. La equidad en universidad también existe pero se manifiesta de manera diferente que en secundaria.',
                'resp_cat4_p2' => 'Sí, conozco la Estrategia Nacional de IA del MEP 2026 porque la seguí durante su desarrollo. En la universidad hemos tenido algunas charlas pero no capacitación pedagógica profunda. Como docente que viene de la industria tech, tengo bastante familiaridad con las herramientas, pero la parte pedagógica — cómo integrarlas para maximizar el aprendizaje — es donde más necesito orientación formal.',
                'resp_cierre'  => 'Creo que estamos en el momento más importante para tomar decisiones sobre cómo integrar la IA en la educación de programadores. Las decisiones que tomemos ahora van a formar a la generación de profesionales que va a trabajar con estas herramientas durante los próximos veinte años. Eso le da mucho peso a esta investigación.',
                'observaciones' => '',
            ],

            // ── D-11 · Universidad · 8-15 años · escéptico del hype ─────────
            [
                'codigo_participante' => 'D-11',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'Universidad Latina de Costa Rica',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => '8 a 15 años',
                'cursos_actuales'     => 'Fundamentos de Programación, Bases de Datos, Seguridad Informática',
                'resp_cat1_p1' => 'En diez años de docencia universitaria he visto pasar muchas modas tecnológicas que iban a "revolucionar" la educación, y la mayoría no cumplió las expectativas. Las dificultades fundamentales de aprender programación siguen siendo las mismas: pensamiento lógico, abstracción y tolerancia a la frustración. Los estudiantes se bloquean cuando tienen que enfrentar la ambigüedad — cuando no hay una respuesta única y correcta. La diferencia entre sintaxis y diseño es que una tiene respuestas en el libro y el otro requiere juicio, y el juicio se desarrolla con práctica, no con herramientas.',
                'resp_cat1_p2' => 'Es un problema estructural de la educación en programación, no específico de mis estudiantes. El enfoque predominante en tutoriales y cursos en línea es enseñar sintaxis en ejemplos aislados, nunca en el contexto de un sistema real. Los estudiantes llegan acostumbrados a eso y cuando tienen que construir algo con arquitectura, no tienen los andamiajes conceptuales para hacerlo. El problema es visible desde los primeros proyectos integradores.',
                'resp_cat1_p3' => 'Lo que mejor funciona es la exposición sostenida a código bien escrito y la discusión de por qué está bien escrito. Los estudiantes necesitan modelos mentales de lo que es código de calidad antes de poder producirlo. Lo que no funciona es introducir múltiples conceptos nuevos simultáneamente — la curva cognitiva se vuelve demasiado empinada. La simplificación progresiva es clave.',
                'resp_cat2_p1' => 'Sí, y lo veo con preocupación creciente. El uso es muy frecuente y principalmente para evadir el proceso de aprendizaje, no para apoyarlo. Lo noto en que el código entregado tiene un nivel muy superior al trabajo en clase, y en que los estudiantes no pueden responder preguntas básicas sobre su propio código. Lo hacen de forma disimulada en su mayoría, aunque algunos son bastante abiertos.',
                'resp_cat2_p2' => 'Los problemas son múltiples. El más grave es la atrofia del pensamiento computacional: si nunca tienen que resolver un problema desde cero, nunca desarrollan esa capacidad. También he notado mayor dificultad en los exámenes presenciales y una disminución en la calidad de las preguntas que hacen en clase — las preguntas se vuelven más superficiales. He tenido casos de deshonestidad académica, pero el proceso disciplinario es complejo y consume mucho tiempo.',
                'resp_cat2_p3' => 'La política de la universidad es ambigua — menciona la IA pero no da directrices claras. Yo la restringo en evaluaciones y lo explico desde el primer día de clase. He rediseñado mis exámenes para que sean más contextuales y menos reproductivos — es difícil que la IA resuelva un problema que requiere aplicar conceptos específicos del curso a un contexto nuevo que presenté en la última clase.',
                'resp_cat3_p1' => 'Con reservas importantes, sí. El potencial existe pero está muy condicionado por cómo se use. Si se usa para que el estudiante explore, cometa errores y reciba retroalimentación inmediata, puede ser valioso. Si se usa para evadir el proceso de pensamiento, es contraproducente. El problema es que la segunda modalidad es mucho más fácil y natural, y sin una guía pedagógica explícita, es lo que predomina.',
                'resp_cat3_p2' => 'La adoptaría con escepticismo pero con apertura. Lo que necesitaría ver es evidencia de que efectivamente mejora el aprendizaje real — no el rendimiento académico, sino la comprensión profunda. Lo que más resistencia me generaría es si la guía asume que la IA siempre ayuda, sin reconocer los casos donde puede obstaculizar el aprendizaje.',
                'resp_cat3_p3' => 'Es una distinción crucial. El que pide razonamiento está aprendiendo; el que pide código está ejecutando. Pero hay que ser honesto: la segunda forma es infinitamente más fácil y rápida, y en un contexto de estudiantes con muchas materias y poco tiempo, el camino corto es muy tentador. He visto muy pocos estudiantes que usen la IA para aprender genuinamente — son excepciones. El problema es sistémico, no individual.',
                'resp_cat4_p1' => 'El acceso en la universidad es razonablemente bueno pero desigual. Hay estudiantes que trabajan jornada completa, que estudian de noche, y que tienen recursos limitados. La brecha no es solo de acceso a dispositivos sino de tiempo y de capacidad cognitiva disponible cuando finalmente se sientan a estudiar. Esa realidad tiene que informar cualquier propuesta pedagógica.',
                'resp_cat4_p2' => 'Tengo conocimiento general de las iniciativas del MEP relacionadas con IA, aunque no todos los detalles de la Estrategia 2026. En la universidad hemos tenido algunas actividades informativas pero no capacitación pedagógica estructurada. Soy escéptico de las capacitaciones cortas sobre tecnología — el problema pedagógico requiere una formación más profunda que un taller de dos horas.',
                'resp_cierre'  => 'Mi postura es que antes de adoptar cualquier herramienta nueva, deberíamos preguntarnos qué problema pedagógico específico resuelve y qué problemas nuevos introduce. La IA generativa introduce problemas nuevos importantes: dependencia, superficialidad, y atrofia del pensamiento. Si la guía de prompts que propone esta investigación ayuda a mitigar esos problemas, vale la pena. Si solo facilita el uso sin abordarlo críticamente, puede hacer más daño que bien.',
                'observaciones' => '',
            ],

            // ── D-12 · Universidad · +15 años · filosófico, humanista ────────
            [
                'codigo_participante' => 'D-12',
                'fecha_hora'          => '17/06/2026',
                'institucion'         => 'Universidad Latina de Costa Rica',
                'modalidad'           => 'Auto-aplicado (en línea)',
                'years_experiencia'   => 'Más de 15 años',
                'cursos_actuales'     => 'Ingeniería de Software, Ética en Tecnología, Proyecto de Graduación',
                'resp_cat1_p1' => 'Después de más de quince años enseñando ingeniería de software, mi convicción es que la dificultad central en programación no es técnica sino epistémica: los estudiantes no saben qué significa entender algo. Pueden repetir definiciones, pueden copiar patrones, pero no saben cómo saber si realmente comprenden. El bloqueo más profundo ocurre cuando se enfrentan a la incertidumbre — cuando no hay respuesta en el libro ni en internet. La diferencia entre sintaxis y diseño es la diferencia entre conocimiento y comprensión, y la educación universitaria, en general, entrena mejor el primero que el segundo.',
                'resp_cat1_p2' => 'La arquitectura por capas es un caso particular de un problema más general: la incapacidad de pensar en términos de responsabilidades y límites. Los estudiantes piensan en código, no en sistemas. La dificultad se manifiesta en código acoplado, sin interfaces, sin posibilidad de prueba unitaria. Es un síntoma de que nunca han tenido que mantener código propio escrito seis meses atrás — ese ejercicio, más que cualquier clase, enseña por qué la arquitectura importa.',
                'resp_cat1_p3' => 'A lo largo de los años he llegado a creer que la mejor estrategia pedagógica para el diseño de sistemas es la práctica reflexiva: hacer, observar las consecuencias, reflexionar, ajustar. Lo que mejor ha funcionado es el proyecto longitudinal que dura todo el semestre y va creciendo en complejidad — los estudiantes viven en carne propia el costo de las malas decisiones tempranas. Lo que no funciona es cualquier aproximación que separe el pensar del hacer.',
                'resp_cat2_p1' => 'Lo observo como un fenómeno sociocultural importante, no solo pedagógico. Los estudiantes universitarios actuales tienen una relación fundamentalmente diferente con el conocimiento: están acostumbrados a que las respuestas estén disponibles instantáneamente. La IA es la culminación de esa tendencia. Lo usan de forma muy abierta y sin culpa, lo que en sí mismo es un dato interesante sobre cómo perciben el aprendizaje.',
                'resp_cat2_p2' => 'El problema más profundo que veo es lo que podría llamarse la ilusión de competencia: el estudiante siente que sabe porque tiene el código funcionando, pero no ha desarrollado el modelo mental que le permitiría construirlo en un contexto diferente. Eso es especialmente grave en ingeniería de software, donde las situaciones nuevas son la norma. La deshonestidad académica existe, pero el problema de fondo es que el sistema de evaluación tradicional incentiva la obtención de resultados sobre la comprensión del proceso.',
                'resp_cat2_p3' => 'En la universidad existe una política general de integridad académica actualizada, pero su aplicación en el contexto de la IA es complicada porque la herramienta es nueva y los criterios éticos no están del todo definidos. Yo he optado por un enfoque de transparencia total: el uso de IA está permitido y documentado, y las evaluaciones están diseñadas para que el proceso sea más importante que el resultado.',
                'resp_cat3_p1' => 'Sí, tiene potencial pedagógico, pero quiero ser preciso sobre qué tipo de potencial. La IA puede ser un excelente interlocutor socrático si el estudiante sabe hacer las preguntas correctas. Puede acelerar el ciclo de retroalimentación que es fundamental para el aprendizaje. Puede hacer que el estudiante tenga acceso a un "tutor" siempre disponible. Pero ninguna de esas funciones se realiza automáticamente — requieren diseño pedagógico intencional. Sin ese diseño, la IA se convierte simplemente en una máquina de hacer trampa más sofisticada.',
                'resp_cat3_p2' => 'Estaría dispuesto a explorarla, con la condición de que esté fundamentada en una comprensión profunda de cómo aprenden las personas, no solo en cómo funciona la tecnología. Lo que más me generaría resistencia es una guía tecnocéntrica que trate la IA como solución y no como herramienta — las herramientas no enseñan, los docentes sí. La guía debería empoderar al docente, no sustituirlo.',
                'resp_cat3_p3' => 'Es la distinción entre la epistemología del consumidor y la del aprendiz. El que pide código es un consumidor de respuestas; el que pide razonamiento está en un proceso de construcción de conocimiento. Pero hay algo más sutil: incluso pedir razonamiento a la IA puede ser una forma de evasión si el estudiante acepta pasivamente la explicación sin verificarla, sin cuestionarla, sin reelaborarla. El aprendizaje genuino requiere que el estudiante construya activamente su comprensión, y eso no lo puede hacer ninguna herramienta por él.',
                'resp_cat4_p1' => 'La inequidad existe en todos los niveles educativos, incluida la universidad privada. Hay estudiantes que trabajan, que tienen responsabilidades familiares, que estudian en condiciones difíciles. La brecha digital no es solo de acceso a dispositivos sino de capital cultural: saber qué preguntas hacer, cómo evaluar la información, cómo aprender de forma autónoma. Esas competencias no se distribuyen equitativamente en la sociedad costarricense.',
                'resp_cat4_p2' => 'Conozco bien la Estrategia Nacional de IA del MEP 2026 y he participado en algunos espacios de discusión al respecto. En la universidad hemos tenido varias iniciativas de sensibilización, aunque la capacitación pedagógica profunda es escasa. Lo que más necesitamos no es capacitación técnica sino espacio para reflexionar colectivamente sobre las implicaciones pedagógicas y éticas de integrar estas herramientas.',
                'resp_cierre'  => 'La pregunta que subyace a toda esta investigación — y que creo que es la más importante — es: ¿qué tipo de personas queremos formar? ¿Formamos programadores que saben usar herramientas, o formamos pensadores que pueden crear soluciones ante problemas que todavía no existen? La IA nos obliga a responder esa pregunta con claridad, porque si formamos solo lo primero, la IA lo va a hacer mejor que nosotros. La educación tiene que apostar por lo que la IA no puede reemplazar: el juicio, la creatividad, la responsabilidad ética y la comprensión profunda. Eso es lo que deberíamos estar enseñando, con o sin IA.',
                'observaciones' => '',
            ],

        ];

        foreach ($docentes2 as $data) {
            Entrevista::firstOrCreate(['codigo_participante' => $data['codigo_participante']], $data);
        }
    }
}
